# Generated by Django 4.2.6 on 2023-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('total_runs', models.IntegerField()),
                ('total_wickets', models.IntegerField()),
                ('batting_average', models.FloatField()),
                ('bowling_average', models.FloatField(blank=True, null=True)),
                ('recent_match_scores', models.TextField()),
                ('team_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
