# Generated by Django 4.2.6 on 2023-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField()),
                ('news_photo', models.TextField()),
                ('news_desc', models.TextField()),
            ],
        ),
    ]
