# Generated by Django 3.2.18 on 2023-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.TextField(),
        ),
    ]
