# Generated by Django 4.2.6 on 2023-11-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='images/img1.jpg', upload_to='venue_images/'),
        ),
    ]
