# Generated by Django 4.2.6 on 2023-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_embed_link',
            field=models.TextField(blank=True),
        ),
    ]
