# Generated by Django 4.2.6 on 2023-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField()),
                ('match_team1', models.CharField(max_length=20)),
                ('match_team1_flag', models.CharField(max_length=20)),
                ('match_team2', models.CharField(max_length=20)),
                ('match_team2_flag', models.CharField(max_length=20)),
                ('match_result', models.TextField()),
                ('match_date', models.CharField(max_length=30)),
                ('match_your_time', models.CharField(max_length=15)),
                ('match_local_time', models.CharField(max_length=15)),
                ('match_venue', models.TextField()),
                ('match_highlights', models.TextField()),
            ],
        ),
    ]
